{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "MegaLinter Configuration Schema",
  "description": "Schema for validating MegaLinter configuration files.",
  "type": "object",
  "properties": {
    "APPLY_FIXES": {
      "type": "string",
      "enum": ["all", "none", "default"],
      "description": "Specify whether to apply fixes automatically."
    },
    "DISABLE": {
      "type": "array",
      "items": { "type": "string" },
      "description": "List of linters or languages to disable."
    },
    "DISABLE_LINTERS": {
      "type": "array",
      "items": { "type": "string" },
      "description": "List of specific linters to disable."
    },
    "DISABLE_ERRORS_LINTERS": {
      "type": "array",
      "items": { "type": "string" },
      "description": "List of linters for which errors should be disabled."
    },
    "PRINT_ALL_FILES": {
      "type": "boolean",
      "description": "Whether to print all files checked by the linter."
    },
    "FILTER_REGEX_EXCLUDE": {
      "type": "string",
      "description": "Regex pattern to exclude files from linting."
    },
    "PRE_COMMANDS": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "command": {
            "type": "string",
            "description": "Command to execute."
          },
          "cwd": {
            "type": "string",
            "description": "Working directory for the command."
          },
          "continue_if_failed": {
            "type": "boolean",
            "description": "Whether to continue execution if this command fails."
          },
          "venv": {
            "type": "string",
            "description": "Virtual environment to use for the command."
          }
        },
        "required": ["command", "cwd"],
        "additionalProperties": false
      },
      "description": "List of commands to run before linting."
    },
    "POST_COMMANDS": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "command": {
            "type": "string",
            "description": "Command to execute."
          },
          "cwd": {
            "type": "string",
            "description": "Working directory for the command."
          },
          "continue_if_failed": {
            "type": "boolean",
            "description": "Whether to continue execution if this command fails."
          },
          "venv": {
            "type": "string",
            "description": "Virtual environment to use for the command."
          }
        },
        "required": ["command", "cwd"],
        "additionalProperties": false
      },
      "description": "List of commands to run after linting."
    },
    "REPORTER": {
      "type": "string",
      "enum": ["json", "fileio", "email", "github-status"],
      "description": "Specify the type of reporting."
    },
    "SHOW_ELAPSED_TIME": {
      "type": "boolean",
      "description": "Whether to display elapsed time for linting."
    },
    "PLUGINS": {
      "type": "array",
      "items": { "type": "string", "format": "uri" },
      "description": "List of plugin URLs to use with MegaLinter."
    },
    "MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS": {
      "type": "boolean",
      "description": "Disable errors for Markdown link check linter."
    },
    "YAML_YAMLLINT_FILTER_REGEX_EXCLUDE": {
      "type": "string",
      "description": "Regex pattern to exclude YAML files from Yamllint."
    }
  },
  "additionalProperties": false
}
